/**
 * 冒泡消息
 */
export enum BubbleMessage {
  OPEN_LINK = 'OPEN_LINK',
  LINE_CHANGE_SIZE = 'LINE_CHANGE_SIZE',
  NEED_DRAW = 'NEED_DRAW',
  NEED_LAYOUT = 'NEED_LAYOUT',
  CONTENT_CHANGE = 'CONTENT_CHANGE',
  NEED_LAYOUT_LISTITEM = 'NEED_LAYOUT_LISTITEM',
  UPDATE_CONTENT_HEIGHT = 'UPDATE_CONTENT_HEIGHT',
  UPDATE_CONTENT_LENGTH = 'UPDATE_CONTENT_LENGTH',
}
