/**
 * 冒泡消息
 */
export enum BubbleMessage {
  OPEN_LINK = 'OPEN_LINK',
  LINE_CHANGE_SIZE = 'LINE_CHANGE_SIZE',
  NEED_DRAW = 'NEED_DRAW',
  NEED_LAYOUT = 'NEED_LAYOUT',
  CONTENT_CHANGE = 'CONTENT_CHANGE',
}
