export enum EventName {
  EDITOR_CHANGE_SIZE = 'EDITOR_CHANGE_SIZE',

  DOCUMENT_CHANGE_SELECTION = 'DOCUMENT_CHANGE_SELECTION',
  DOCUMENT_CHANGE_SIZE = 'DOCUMENT_CHANGE_SIZE',

  LINE_CHANGE_SIZE = 'LINE_CHANGE_SIZE',
}
