/**
 * 事件枚举
 */
export enum EventName {
  EDITOR_CHANGE_SIZE = 'EDITOR_CHANGE_SIZE',
  EDITOR_CHANGE_FORMAT = 'EDITOR_CHANGE_FORMAT',
  EDITOR_COMPOSITION_START = 'EDITOR_COMPOSITION_START',
  EDITOR_COMPOSITION_UPDATE = 'EDITOR_COMPOSITION_UPDATE',
  EDITOR_COMPOSITION_END = 'EDITOR_COMPOSITION_END',
  EDITOR_CHANGE_SEARCH_RESULT = 'EDITOR_CHANGE_SEARCH_RESULT',

  EDITOR_CHANGE_HISTORY_STACK = 'EDITOR_CHANGE_HISTORY_STACK',
  EDITOR_CHANGE_CONTENT = 'EDITOR_CHANGE_CONTENT',

  DOCUMENT_CHANGE_SELECTION = 'DOCUMENT_CHANGE_SELECTION',
  DOCUMENT_CHANGE_SELECTION_RECTANGLE = 'DOCUMENT_CHANGE_SELECTION_RECTANGLE',
  DOCUMENT_CHANGE_SIZE = 'DOCUMENT_CHANGE_SIZE',
  DOCUMENT_CHANGE_CONTENT = 'DOCUMENT_CHANGE_CONTENT',
  DOCUMENT_CHANGE_FORMAT = 'DOCUMENT_CHANGE_FORMAT',

  DOCUMENT_CHANGE_SEARCH_RESULT = 'DOCUMENT_CHANGE_SEARCH_RESULT',

  DOCUMENT_NEED_LAYOUT = 'DOCUMENT_NEED_LAYOUT',
  DOCUMENT_NEED_DRAW = 'DOCUMENT_NEED_DRAW',

  HISTORY_STACK_CHANGE = 'HISTORY_STACK_CHANGE',
}
